### PR TITLE
Column rearraning and placeholders for ITG-85

### PR DESCRIPTION
**Pull request by jfalkner**
This code rearranges stuff to match Remy's requested list. In the case of columns that didn't exist before, placeholders are there. I'll add the calculated values in the next PR.

See https://jira.pacificbiosciences.com/browse/ITG-85

### CODE REVIEW

**Comment by jfalkner** [comment]
Just removed the WIP comment. I spot checked the CSV files and they appear correct. The rearrangement was tedious but straight-forward. Probably fine to merge as-is.

I'll ping @evolvedmicrobe in case he has time to take a look.

**Comment by evolvedmicrobe** [comment]
Hi Jayson,

These changes look fine and are totally a-okay to merge. Some general comments on this file though from my end (not things that need to be fixed, but just to help you understand my coding preferences).


* It's nice to indicate the relationship between variables where they are declared instead of when they are later used.  Todo/Get are related but are unrelated when defined.  Perhaps to make it clearer and avoid repeated definitions you could use:

```
def Todo(key):
    return Get(key, transform= (lambda x: ""))
```
I know this was temporary copy-pasta though so I understand that's persnickety ;)

* Prefer streaming things in and out rather than holding them in memory - In this case I don't think it matters since we are not building giant files, but in general I often find myself refactoring code that was originally intended for small datasets but is now used by large datasets.  In theory you could create a row and write it to disk immediately without storing it, so that enumerate/consume design is my preferred go to pattern.  Again though, it doesn't matter here.

* The eol_qc_movie_stats function.  This defines one long list of headers, and another long list of stuff to grab data and add them to the rows.  This isn't a great design because it often leads to bugs where the order of the two items doesn't line up, and makes for unnecessarily verbose code.  It would have been nice to this be stylistically similar to the eol_qc_zmws_stats method

* Line 109-111 - Seems like a good place to put a list comprehension. I didn't see any in this code, and it's totally a style preference, but if they're new to you they can make for cleaner code so pointed it out

* Lines 389/390 - These two lines are effectively redundant, and ideally only one logging mechanism is used.

```
    print fname
    log.info("Writing {:}".format(fname))
```

**Comment by jfalkner** [comment]
@evolvedmicrobe I agree with the notes and the work here is intended to be an MVP that extends the existing python code that was made. I'll stick with least work to get EOL QC operating then a heavier refactor later. Ideally, when I've had time to think through breaking this code out of pbinternal2 (the monolith seems unhelpful and unneeded) and recasting it to match the new repos and build systems.

I'll do a quick pass to roll in suggested changes that are quick then merge.

**Comment by jfalkner** [comment]
> ```
 def Todo(key):
    return Get(key, transform= (lambda x: ""))
```

This won't work. If you look at Get, it assumes use of `getattr` then applied transform. You can't use it unless the named column exists. In other words, `transform` doesn't replace the failing logic. I'm leaving as-is. It'd have been nice to link the two concepts in the code, but works as-is.

**Comment by jfalkner** [comment]
> Prefer streaming things in and out rather than holding them in memory

Yeah, too much of a refactor here. IMO, stream in a chunked fashion so that small files end up auto-buffered in memory and big files end up with efficient disk writes.

**Comment by jfalkner** [comment]
> The eol_qc_movie_stats function. This defines one long list of headers, and another long list of stuff to grab data and add them to the rows. 

Yep, not great but I double-checked that the rearrangement looks correct. Sticking with the old style until we do a bigger refactor.

**Comment by jfalkner** [comment]
> Lines 389/390 - These two lines are effectively redundant, and ideally only one logging mechanism is used.

I didn't consider cleaning up any logging. There are also chunks of commented out code. I'll leave them as-is since these don't matter. smrtlink hides all of this output anyhow.

**Comment by mpkocher** [comment]
The return type from`Get` is a callable with `__name__` defined. The `__name__` will be used as the attribute name in the CSV.

```python
def todo(name):
    def f(*args, **kwargs):
        return ""
    f.__name__ = name
    return f
```

I agree with Nigel, we should try to write in a streaming fashion, specifically for the per ZMW usecase. By eye, this looks like a minor 5 line change.

```python
    column_names = [a.__name__ for a in acc]
    header = ",".join([str(x) for x in column_names])

    with open(outcsv, 'w') as fh:
        fh.write(header + "\n")
        for read in aset:
            row = []
            sread = ReadShare(read)
            for fun in acc:
                row.append(fun(sread))
            fh.write(','.join(map(str, row)) + "\n")
```

In general, I think this code is well written and designed. Using the python stdlib to write the CSV might be a useful improvement for consistency.  However, I see these potential changes as a minor improvements. I currently don't see a need for any large refactor effort.

**Comment by evolvedmicrobe** [comment]
> stream in a chunked fashion so that small files end up auto-buffered in memory and big files end up with efficient disk writes.

I am not entirely sure what you mean here.  Everything should be auto buffered by default, since a python `open()` call will initiate use a buffer of size ~8kb for writing to files to make the operations efficient (it flushes on line end for tty devices).

**Pull request merged**
